// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Cv_s24vW3hDLKDYZtxha51x6I0QFHqY',
    appId: '1:633943818159:web:095e4a0e0bdbb917b7795a',
    messagingSenderId: '633943818159',
    projectId: 'texturaqr',
    authDomain: 'texturaqr.firebaseapp.com',
    storageBucket: 'texturaqr.firebasestorage.app',
    measurementId: 'G-Q1DZE0Z6F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_DGWW7e1nC2S5ycJOg4t8xnxU85DpD4',
    appId: '1:633943818159:android:c04df2ac725a6908b7795a',
    messagingSenderId: '633943818159',
    projectId: 'texturaqr',
    storageBucket: 'texturaqr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rkAJlQaIIX994FUhj-Ukzy40J3e9tPA',
    appId: '1:633943818159:ios:e1fd2f3f0aa15365b7795a',
    messagingSenderId: '633943818159',
    projectId: 'texturaqr',
    storageBucket: 'texturaqr.firebasestorage.app',
    androidClientId: '633943818159-mlk2s8nfju22fk7v95t93menpm0j7hi5.apps.googleusercontent.com',
    iosClientId: '633943818159-1r81t6l9l5tn7fau72br8nhk6ibeh6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.texuraqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rkAJlQaIIX994FUhj-Ukzy40J3e9tPA',
    appId: '1:633943818159:ios:e1fd2f3f0aa15365b7795a',
    messagingSenderId: '633943818159',
    projectId: 'texturaqr',
    storageBucket: 'texturaqr.firebasestorage.app',
    androidClientId: '633943818159-mlk2s8nfju22fk7v95t93menpm0j7hi5.apps.googleusercontent.com',
    iosClientId: '633943818159-1r81t6l9l5tn7fau72br8nhk6ibeh6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.texuraqr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Cv_s24vW3hDLKDYZtxha51x6I0QFHqY',
    appId: '1:633943818159:web:f47cfd81f34367c9b7795a',
    messagingSenderId: '633943818159',
    projectId: 'texturaqr',
    authDomain: 'texturaqr.firebaseapp.com',
    storageBucket: 'texturaqr.firebasestorage.app',
    measurementId: 'G-H550MN2MM0',
  );
}
